version: '3.8'

services:
  psqldb:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - 5432:5432

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
